### ISSUE TITLE
FlowRouter no longer supports middleware

### ISSUE THREAD

**Issue by dovrosenberg** [meteor-useraccounts/flow-routing#1]
FlowRouter has deprecated middleware in favor of [triggers] (https://github.com/kadirahq/flow-router#triggers), so ensureSignedIn should really be a trigger to be used globally on enter:

`FlowRouter.triggers.enter([ensureSignedIn], {except: ['loggedOut']});`

where it takes parameters for context and redirect.  I'd try to provide a pull request, but I'm not sure I understand the UserAccounts code well enough.  I wrote one for the old AccountsEntry package that looked like:

    ensureSignedIn = function(context, redirect) {
        if (!_.contains(AccountsEntryRouteList, context.route.name) && !Meteor.loggingIn() && !Meteor.user()) {
            Session.set('fromWhere', context.path);
            redirect('/sign-in');
            return Session.set('entryError', 'error.signInRequired');
        }
    };

**Comment by jshimko** [comment]
Hey @dovrosenberg, this was taken care of in the `ensure-signed-in` branch of this repo, but it wasn't merged yet.  I just merged everything into master so people can start using/testing it.  

If you want to protect a route, you'd do this:

```js
FlowRouter.route('/private', {
  triggersEnter: [AccountsTemplates.ensureSignedIn],
  action: function() {
    BlazeLayout.render(...)
  }
});
```

Or if you want to protect ALL routes:

```js
FlowRouter.triggers.enter([AccountsTemplates.ensureSignedIn]);
```

I also added a helper for doing the auth check at the template level instead of depending on routes/redirects.

So, if you wanted to secure a specific template, you could add that template like this:

```handlebars
{{> ensureSignedIn template="myTemplate"}}
```
and that will render the default `fullPageAtForm` template from your chosen User Accounts templates package (bootstrap, materialize, etc).  Once signed in, it'll render `myTemplate` in place of the form.   

If you want to declare a custom sign in template instead of `fullPageAtForm`, you would do this:

```handlebars
{{> ensureSignedIn template="myTemplate" auth="myLoginForm"}}
```
And that custom auth template just needs to include `{{> atForm}}` somewhere in it.  The only reason you'd use this optional feature is if you wanted to modify the layout around the `atForm` template (like
`fullPageAtForm` does).

As I type this, I'm also realizing this template helper should be in core instead of the routing package, but it's here for now, so test away!

**Comment by jshimko** [comment]
FYI, template level content protection has been removed from this package in favor of adding it to core.  Will be available as soon as my pull request is merged.  

See https://github.com/meteor-useraccounts/core/pull/496

**Comment by dovrosenberg** [comment]
Awesome.  Thanks!
