### ISSUE TITLE
Redirect to previous route after successful login not working

### ISSUE THREAD

**Issue by st3phan** [meteor-useraccounts/flow-routing#16]
My config for a custom sign-in route:

````javascript
AccountsTemplates.configureRoute('signIn', {
    name: 'signIn',
    path: 'sign-in',
    template: 'signIn',
    layoutTemplate: 'layout',
    layoutRegions: {},
    contentRegion: 'template',
});
````
The private route successfully redirects to the custom sign-in template using a trigger:

````javascript
FlowRouter.route('/private', {
    triggersEnter: [AccountsTemplates.ensureSignedIn],
    name: 'private',
    action: function (params, queryParams) {
        BlazeLayout.render('layout', { template: 'private' });
    }
})
```
But after a successful login it doesn't redirect back to the '/private' route. This should be default behaviour right? Or am I missing something?

This is my sign-in template: 

````html
<template name="signIn">
    <button>Login</button>
</template>
````

````javascript
Template.signIn.events({
    'click button': function(e) {
        Meteor.loginWithPassword('foo@bar.com', 'password', function(err) {
            if (err) {
                console.log(err)
            }
        });
    }
});

**Comment by splendido** [comment]
I think the problem is you're using your custom helper to call `Meteor.loginWithPassword`.
All logic and redirects provided with useraccounts packages happens with its custom helpers: for example [these lines](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L173-L175) are those using a callback to possibly redirects the user somewhere after the login.

If your `signIn` template only needs to call `Meteor.loginWithPassword` try to change it to match the original lines.

**Comment by splendido** [comment]
The thing about providing custom templates is a little more complicated and you can find some discussion about it among the issues of the core repo. For example lets have a look at [This](https://github.com/meteor-useraccounts/core/issues/366#issuecomment-96380408) comment, but you can also read https://github.com/meteor-useraccounts/core/issues/212.

**Comment by splendido** [comment]
@st3phan, any update on this?
